fix several issues
Sopamo/via pull request #4
Opened 2022-07-27 19:36 UTC by fieteboerner

- fix edit action if no editor command exists
- set current project before all commands are started
- check file existence before try to delete it

2022-07-28 08:00 UTC, Sopamo requested changes

2022-07-28 08:00 UTC, Sopamo commented on src/commands/editProject.ts
> +        cmd: ['sh', '-c', 'if [ command -v editor 2> /dev/null ]; then echo -n "editor"; else echo -n "${EDITOR:-vi}"; fi'],
This doesn't work properly on OSX. For example, it returns `-n nano` instead of `nano`:

```
deno run --allow-read --allow-run --allow-env --allow-write ./src/via.ts keelearning edit                            [9:57:14]
Running -n nano /Users/paulmohr/.via/projects/keelearning.yaml in /Users/paulmohr/.via
sh: - : invalid option
Usage:  sh [GNU long option] [option] ...
        sh [GNU long option] [option] script-file ...
```

2022-07-28 10:40 UTC, fieteboerner commented on src/commands/editProject.ts
> +        cmd: ['sh', '-c', 'if [ command -v editor 2> /dev/null ]; then echo -n "editor"; else echo -n "${EDITOR:-vi}"; fi'],
does it work if we omit the `-n` options of the echo commands? seems it is not possible to pass options this way in osx? In order we trim the output, it still should work.  - could you please try? I have no chance to test it on osx.

2022-07-29 07:29 UTC, Sopamo commented on src/commands/editProject.ts
> +        cmd: ['sh', '-c', 'if [ command -v editor 2> /dev/null ]; then echo -n "editor"; else echo -n "${EDITOR:-vi}"; fi'],
Yes that works! You've been trimming the output already anyway, so it just works without the `-n`. I pushed the tested change, so if that looks good to you feel free to merge the PR :)

2022-07-29 07:29 UTC, Sopamo approved these changes

2022-07-29 13:15 UTC, fieteboerner commented on src/commands/editProject.ts
> +        cmd: ['sh', '-c', 'if [ command -v editor 2> /dev/null ]; then echo -n "editor"; else echo -n "${EDITOR:-vi}"; fi'],
thats great. thanks for testing!

2022-07-29 13:16 UTC, merged